# serverless.yml

service: ffcs-bus-track-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.dudewheresmybus.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  routesTableName: 'routes-table-${self:provider.stage}'
  pointsOfInterestTableName: 'points-of-interest-table-${self:provider.stage}'
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - { "Fn::GetAtt": ["RoutesDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["PointsOfInterestDynamoDBTable", "Arn" ] }
  environment:
    ROUTES_TABLE: ${self:custom.routesTableName}
    POINTS_OF_INTEREST_TABLE: ${self:custom.pointsOfInterestTableName}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
        cors: true

resources:
  Resources:
    RoutesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: routeId
            AttributeType: S
        KeySchema:
          -
            AttributeName: routeId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.routesTableName}
    PointsOfInterestDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: pointOfInterestId
            AttributeType: S
        KeySchema:
          - AttributeName: pointOfInterestId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.pointsOfInterestTableName}
